baseURL = "https://example.com"
languageCode = "en-us"
title = "Mixedpaper"
theme = "mixedpaper"
enableRobotsTXT = true
paginate = 3 # Set the number of posts to show before overflowing to the next page.
summaryLength = 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses = true # enable theme-defined highlight style
hasCJKLanguage = false

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

[taxonomies]
tag = "tags"

[author]
name = "Hugo Author"

[params]
# Blog description at the top of the homepage. Supports markdown.
description = "Mixedpaper is a minimalist Hugo theme, perfect for writers and bloggers."
showReadMore = false
mainSections = [
	"post",
]
# paginate of archives, tags and categories
listPaginate = 20
postLicense = ""

[params.comment]
type = "none"

# Add your Disqus shortname here.
disqusShortname = ""

[params.comment.valine]
appid = "your-appid"
appkey = "your-appkey"
placeholder = "enjoy~"
avatar = "mm"
pageSize = 10.0
visitor = false
recordIP = true
highlight = true
meta = "nick,mail"
requiredFields = "nick,mail"

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
